export const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS';
export const SET_WALLET_CONNECTING = 'SET_WALLET_CONNECTING';
export const SET_WALLET_CONNECTED = 'SET_WALLET_CONNECTED';


export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_TRANSACTIONS_LOADING = 'SET_TRANSACTIONS_LOADING';
export const SET_TRANSACTIONS_LOADED = 'SET_TRANSACTIONS_LOADED';
